### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by Dangle76** [Ikana/electron-cli#2]
When attempting to electron-cli init (or any electron-cli command) after NPM install, returning:

C:\Users\XXXX\AppData\Roaming\npm\node_modules\electron-cli\node_modules\ora\index.js:2
const chalk = require('chalk');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\XXXX\AppData\Roaming\npm\node_modules\electron-cli\dist\commands\init.js:28:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by Ikana** [comment]
Which version of node are you using??

**Comment by Dangle76** [comment]
0.12.2

**Comment by Ikana** [comment]
That error is from ora, a dependency that I don't maintain, i really recommend you update to at least to node 4.x, the 0.12.2 version is too old,  if you have any problems with that hit me up on https://wealljs.slack.com/ my username there is roderik
